apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: project-acc
  sources:
  - repoURL: https://github.com/mojtabaimani/sodeko-platform-tools.git
    path: tools/sealed-secrets
    targetRevision: 0.0.1
    helm:
      releaseName: sealed-secrets
      valueFiles:
        - $values/app-values/sealed-secrets/sealed-secrets-values-acc.yaml
  - repoURL: https://github.com/mojtabaimani/sodeko-green-platform.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        managed: "true"
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
