apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-tst
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: project-tst
  source:
    path: ./app-of-apps/tst
    repoURL: https://github.com/Kuberise/kuberise.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
