apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-green-prd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    team: green
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: green-prd
  source:
    path: ./app-of-apps
    repoURL: https://github.com/mojtabaimani/sodeko-green-services.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-prd.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
